# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scouts BSA Pack 21 & Troop 33 Chittenango, NY 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Information pages for the Scouts BSA Pack 21 and Troop 33 in Chittenango, NY
  Excelent program from boys and girls ages 5 through 18.  Learn how to be a 
  leader while hiking, camping, swimming, canoing, boating, bike riding, exploring
  nature and learning life skills like First Aid, Knots and the safe use of edge 
  tools like Knives, Axes, Saws and the like.
baseurl: "" # the subpath of your site, e.g. /blog
domain: chittenangoscouts.org
url: https://chittenangoscouts.org # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
